# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('yt_video_id', models.CharField(max_length=20, verbose_name='YouTube stream/video ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
