# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_videoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetarydata',
            name='speed_of_sound',
            field=models.FloatField(help_text='[m/s]', null=True),
        ),
    ]
