# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160402_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='yt_video_id',
            field=models.CharField(max_length=20, null=True, verbose_name='YouTube stream/video ID'),
        ),
    ]
