# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('state', models.CharField(blank=True, choices=[('launch_preparation', 'Launch preparation'), ('countdown', 'Countdown'), ('launch', 'Launch'), ('descent', 'Descent'), ('ground_operations', 'Ground operations'), ('mission_complete', 'Mission complete')], max_length=18)),
                ('mission_time', models.FloatField(help_text='Current mission time in seconds. Negative value means countdown to start')),
                ('cansat_online', models.BooleanField()),
            ],
        ),
    ]
