# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160407_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
