# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160108_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='state',
            new_name='phase',
        ),
    ]
