# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160108_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('mass', models.FloatField(help_text='[kg]', null=True)),
                ('radius', models.FloatField(help_text='[km]', null=True)),
                ('escape_velocity', models.FloatField(help_text='[km/s]', null=True)),
                ('average_density', models.FloatField(help_text='[g/cm³]', null=True)),
                ('earth_similarity_index', models.FloatField(help_text='[0-1]', null=True, verbose_name='Earth Similarity Index')),
                ('avg_atm_molar_mass', models.FloatField(help_text='[g/mol]', null=True, verbose_name='Average molar mass of the atmosphere')),
                ('adiabatic_index', models.FloatField(help_text='> 1.0', null=True)),
                ('atmosphere_density', models.FloatField(help_text='[kg/m³]', null=True, verbose_name='Density of the atmosphere')),
                ('avg_molecule_mass', models.FloatField(help_text='[g]', null=True, verbose_name='Average mass of a single molecule')),
                ('specific_gas_const', models.FloatField(help_text='[J/(K*mol)]', null=True)),
                ('refractive_index', models.FloatField(help_text='> 1.0', null=True)),
                ('molar_refractivity', models.FloatField(help_text='[m³/mol]', null=True)),
                ('atm_speed_of_light', models.FloatField(help_text='[km/s]', null=True, verbose_name='Speed of light in the atmosphere')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
