# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_planetarydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('voltage', models.IntegerField()),
                ('current', models.IntegerField()),
                ('oxygen', models.IntegerField()),
                ('ion_radiation', models.IntegerField(verbose_name='Ionizing radiation')),
                ('humidity', models.DecimalField(decimal_places=2, help_text='0 to 100%, resolution 0.04%', max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='-40 to 125℃, resolution 0.01℃', max_digits=5)),
                ('pressure', models.FloatField(help_text='Air pressure [hPa]')),
                ('gyro_x', models.FloatField(help_text='Angular velocity (X axis) [dps]')),
                ('gyro_y', models.FloatField(help_text='Angular velocity (Y axis) [dps]')),
                ('gyro_z', models.FloatField(help_text='Angular velocity (Z axis) [dps]')),
                ('accel_x', models.FloatField(help_text='Linear acceleration (X axis) [g]')),
                ('accel_y', models.FloatField(help_text='Linear acceleration (Y axis) [g]')),
                ('accel_z', models.FloatField(help_text='Linear acceleration (Z axis) [g]')),
                ('magnet_x', models.FloatField(help_text='Magnetic field (X axis) [gauss]')),
                ('magnet_y', models.FloatField(help_text='Magnetic field (Y axis) [gauss]')),
                ('magnet_z', models.FloatField(help_text='Magnetic field (Z axis) [gauss]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='IMU',
        ),
        migrations.DeleteModel(
            name='SHT',
        )
    ]
