# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160322_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kundt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('frequency', models.FloatField(db_index=True, help_text='[Hz]', unique=True)),
                ('amplitude', models.IntegerField()),
            ],
        ),
    ]
