# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_kundt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='humidity',
            field=models.FloatField(help_text='0 to 100%, resolution 0.04%'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='temperature',
            field=models.FloatField(help_text='-40 to 125℃, resolution 0.01℃'),
        ),
    ]
