# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160323_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetarydata',
            name='specific_gas_const',
            field=models.FloatField(help_text='[J/(K*mol)]', null=True, verbose_name='Specific gas constant'),
        ),
    ]
