# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160323_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps',
            name='fix_type',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='pdop',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='satellites_in_view',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='vdop',
        ),
        migrations.AlterField(
            model_name='gps',
            name='altitude',
            field=models.FloatField(help_text='[m]', null=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='direction',
            field=models.FloatField(help_text='Track Made Good (degrees relative to north) [°]', null=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='hdop',
            field=models.FloatField(help_text='Horizontal Dilution Of Precision', null=True, verbose_name='HDOP'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='speed_over_ground',
            field=models.FloatField(help_text='[km/h]', null=True),
        ),
    ]
